#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

name: kitten

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - .github/workflows/kitten.yml
      - models/kitten/**
      - "!models/kitten/README.adoc"
  schedule:
    - cron: 3 11 3 * *
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      model: kitten
    secrets: inherit
